# Generated by Django 4.0.6 on 2022-07-21 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notepad', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notepads',
            new_name='Notepad',
        ),
    ]
